#! /usr/bin/env bash
#
# Run the first rtog preprocessing method (Tunde's method).

main()
{
    in_dir=nii

    work_dir="$in_dir"_work
    mkdir -p "$work_dir"

    out_dir="$in_dir"_out
    mkdir -p "$out_dir"
    
    if [[ -f "$out_dir"/t1c_bcorr_brain.nii.gz ]] ; then
        if [[ -f "$out_dir"/flair_bcorr_brain.nii.gz ]] ; then
            echo "Processing already complete!"
            exit 1
        fi
    fi

    fsl_anat -i "$in_dir"/t1c.nii -o "$work_dir"/t1c \
        --weakbias --nocrop --noreg --nononlinreg --noseg --nosubcortseg \
        -s 20 -t T1
    fsl_anat -i "$in_dir"/flair.nii -o "$work_dir"/flair \
        --weakbias --nocrop --noreg --nononlinreg --noseg --nosubcortseg \
        -s 20 -t T2

    reg_aladin -ref "$work_dir"/t1c.anat/T1_biascorr.nii.gz \
        -flo "$work_dir"/flair.anat/T2_biascorr.nii.gz \
        -aff "$work_dir"/flair2t1c.txt \
        -res "$work_dir"/flair_t1c_bcorr.nii.gz \
        -rigOnly -omp 6 

    bet "$FSLDIR"/data/standard/MNI152_T1_1mm.nii.gz \
        "$work_dir"/t1c_mni_brain.nii.gz -f 0.5 -g 0 -m

    reg_aladin -ref "$work_dir"/t1c.anat/T1_biascorr.nii.gz \
        -flo "$FSLDIR"/data/standard/MNI152_T1_1mm.nii.gz \
        -aff "$work_dir"/t1c_mni2struct.txt \
        -res "$work_dir"/t1c_mni2struct-nonlin.nii.gz \

    reg_f3d -ref "$work_dir"/t1c.anat/T1_biascorr.nii.gz \
        -flo "$FSLDIR"/data/standard/MNI152_T1_1mm.nii.gz \
        -aff "$work_dir"/t1c_mni2struct.txt \
        -cpp "$work_dir"/t1c_mni2struct-cpp.nii.gz \
        -res "$work_dir"/t1c_bcorr_brain_mask.nii.gz

    reg_resample -ref "$work_dir"/t1c.anat/T1_biascorr.nii.gz \
        -flo "$work_dir"/t1c_mni_brain_mask.nii.gz \
        -cpp "$work_dir"/t1c_mni2struct-cpp.nii.gz\
        -res "$work_dir"/t1c_bcorr_brain_mask.nii.gz
    
    fslmaths "$work_dir"/t1c.anat/T1_biascorr.nii.gz \
        -mas "$work_dir"/t1c_bcorr_brain_mask.nii.gz \
        "$out_dir"/t1c_bcorr_brain.nii.gz
    fslmaths "$work_dir"/flair.anat/T2_biascorr.nii.gz \
        -mas "$work_dir"/t1c_bcorr_brain_mask.nii.gz \
        "$out_dir"/flair_bcorr_brain.nii.gz

    rm -rf "$work_dir"
}

main
